#!/usr/bin/env python3
"""Embed a text file into a C++ header as a raw string literal.

Used to bake host_server/index.html into auto_flash.exe so the client can serve its own
local WebUI without shipping a second file - the deployment path for this client is a
single curl of the exe, and requiring an adjacent index.html would silently degrade the
local UI whenever someone forgot to copy it.
"""

import sys

DELIM = "AFEMBED"


def main() -> int:
    if len(sys.argv) != 4:
        print("usage: embed_file.py <input> <output.h> <symbol>", file=sys.stderr)
        return 2
    src, dst, symbol = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(src, "r", encoding="utf-8") as f:
        text = f.read()

    # A raw literal ends at the first occurrence of )DELIM" - if the payload contained
    # that sequence the generated file would not compile, so fail loudly instead.
    closer = ")" + DELIM + '"'
    if closer in text:
        print(f"error: {src} contains the raw-literal terminator {closer!r}", file=sys.stderr)
        return 1

    with open(dst, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/embed_file.py - do not edit.\n")
        f.write(f"// Source: {src}\n")
        f.write("#pragma once\n\n")
        f.write(f"inline constexpr char {symbol}[] = R\"{DELIM}(")
        f.write(text)
        f.write(f"){DELIM}\";\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
